baseURL: "https://iamlaksh1.github.io/chess/"
languageCode: en-us
title: Abhinav 
theme: PaperMod


permalinks:
  posts: "/:slug"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  defaultTheme: auto
  ShowReadingTime: true
  ShowCodeCopyButtons: true

  homeInfoParams:
    FirstParagraph: >
      Welcome to my personal Chess blog!  
         
    SecondParagraph: >
    
    Title: Houston Chess Olympiad Knights  
   

  socialIcons:
    - name: email
      url: "mailto:houstonchessteam@gmail.com"
    - name: github
      url: "https://github.com/iamlaksh1"
    - name: twitter
      url: "https://twitter.com/iamlaksh1"
 

menu:
  main:
    - name: Posts
      pageRef: /posts/
      weight: 2  
    - identifier: GitHub
      name: GitHub
      url: "https://github.com/iamlaksh1"
      weight: 5
